routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('home');
});*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'management'], function () {
  Route::get('login', 'ManagementAuth\LoginController@showLoginForm')->name('management.login');
  Route::post('login', 'ManagementAuth\LoginController@login');
  Route::post('logout', 'ManagementAuth\LoginController@logout')->name('management.logout');

  Route::get('register', 'ManagementAuth\RegisterController@showRegistrationForm')->name('management.register');
  Route::post('register', 'ManagementAuth\RegisterController@register');

  Route::post('password/email', 'ManagementAuth\ForgotPasswordController@sendResetLinkEmail')->name('management.password.email');
  Route::post('password/reset', 'ManagementAuth\ResetPasswordController@reset')->name('management.password.update');
  Route::get('password/reset', 'ManagementAuth\ForgotPasswordController@showLinkRequestForm')->name('management.password.request');
  Route::get('password/reset/{token}', 'ManagementAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'peminjam'], function () {
  Route::get('login', 'PeminjamAuth\LoginController@showLoginForm')->name('peminjam.login');
  Route::post('login', 'PeminjamAuth\LoginController@login');
  Route::post('logout', 'PeminjamAuth\LoginController@logout')->name('peminjam.logout');

  Route::get('register', 'PeminjamAuth\RegisterController@showRegistrationForm')->name('peminjam.register');
  Route::post('register', 'PeminjamAuth\RegisterController@register');

  Route::post('password/email', 'PeminjamAuth\ForgotPasswordController@sendResetLinkEmail')->name('peminjam.password.email');
  Route::post('password/reset', 'PeminjamAuth\ResetPasswordController@reset')->name('peminjam.password.update');
  Route::get('password/reset', 'PeminjamAuth\ForgotPasswordController@showLinkRequestForm')->name('peminjam.password.request');
  Route::get('password/reset/{token}', 'PeminjamAuth\ResetPasswordController@showResetForm');
});

Route::resource('supplier', 'SupplierController');
Route::resource('barangmasuk', 'BarangMasukController');
Route::resource('barang', 'BarangController');
Route::resource('barangkeluar', 'BarangKeluarController');
Route::resource('pinjambarang', 'PinjamBarangController');
Route::resource('stok', 'StokController');

resources/views/partials/control-sidebar.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
	<!-- Create the tabs -->
	<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
		<li>
			<a href="#control-sidebar-home-tab" data-toggle="tab">
				<i class="fa fa-home"></i>
			</a>
		</li>
		<li>
			<a href="#control-sidebar-settings-tab" data-toggle="tab">
				<i class="fa fa-gears"></i>
			</a>
		</li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<!-- Home tab content -->
		<div class="tab-pane" id="control-sidebar-home-tab">
			<h3 class="control-sidebar-heading">Recent Activity</h3>
			<ul class="control-sidebar-menu">

				<li>
					<a href="javascript:void(0)">
						<i class="menu-icon fa fa-birthday-cake bg-red"></i>
						<div class="menu-info">
							<h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
							<p>Will be 23 on April 24th</p>
						</div>
					</a>
				</li>

				<li>
					<a href="javascript:void(0)">
						<i class="menu-icon fa fa-user bg-yellow"></i>
						<div class="menu-info">
							<h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
							<p>New phone +1(800)555-1234</p>
						</div>
					</a>
				</li>

				<li>
					<a href="javascript:void(0)">
						<i class="menu-icon fa fa-envelope-o bg-light-blue"></i>
						<div class="menu-info">
							<h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
							<p>nora@example.com</p>
						</div>
					</a>
				</li>

				<li>
					<a href="javascript:void(0)">
						<i class="menu-icon fa fa-file-code-o bg-green"></i>
						<div class="menu-info">
							<h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
							<p>Execution time 5 seconds</p>
						</div>
					</a>
				</li>

			</ul> <!-- .control-sidebar-menu -->

			<h3 class="control-sidebar-heading">Tasks Progress</h3>
			<ul class="control-sidebar-menu">

			<li>
				<a href="javascript:void(0)">
					<h4 class="control-sidebar-subheading">
						Custom Template Design
						<span class="label label-danger pull-right">70%</span>
					</h4>
					<div class="progress progress-xxs">
						<div class="progress-bar progress-bar-danger" style="width: 70%"></div>
					</div>
				</a>
			</li>

			<li>
				<a href="javascript:void(0)">
					<h4 class="control-sidebar-subheading">
						Update Resume
						<span class="label label-success pull-right">95%</span>
					</h4>
					<div class="progress progress-xxs">
						<div class="progress-bar progress-bar-success" style="width: 95%"></div>
					</div>
				</a>
			</li>

			<li>
				<a href="javascript:void(0)">
					<h4 class="control-sidebar-subheading">
						Laravel Integration
						<span class="label label-warning pull-right">50%</span>
					</h4>
					<div class="progress progress-xxs">
						<div class="progress-bar progress-bar-warning" style="width: 50%"></div>
					</div>
				</a>
			</li>

			<li>
				<a href="javascript:void(0)">
					<h4 class="control-sidebar-subheading">
						Back End Framework
						<span class="label label-primary pull-right">68%</span>
					</h4>
					<div class="progress progress-xxs">
						<div class="progress-bar progress-bar-primary" style="width: 68%"></div>
					</div>
				</a>
			</li>

			</ul> <!-- .control-sidebar-menu -->
		</div> <!-- .tab-pane -->

		<!-- Stats tab content -->
		<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>

		<!-- Settings tab content -->
		<div class="tab-pane" id="control-sidebar-settings-tab">
			<form method="post">
				<h3 class="control-sidebar-heading">General Settings</h3>

				<div class="form-group">
					<label class="control-sidebar-subheading">
						Report panel usage
						<input type="checkbox" class="pull-right" checked>
					</label>
					<p>Some information about this general settings option</p>
				</div> <!-- .form-group -->

				<div class="form-group">
					<label class="control-sidebar-subheading">
						Allow mail redirect
						<input type="checkbox" class="pull-right" checked>
					</label>
					<p>Other sets of options are available</p>
				</div> <!-- .form-group -->

				<div class="form-group">
					<label class="control-sidebar-subheading">
						Expose author name in posts
						<input type="checkbox" class="pull-right" checked>
					</label>
					<p>Allow the user to show his name in blog posts</p>
				</div> <!-- .form-group -->

				<h3 class="control-sidebar-heading">Chat Settings</h3>

				<div class="form-group">
					<label class="control-sidebar-subheading">
						Show me as online
						<input type="checkbox" class="pull-right" checked>
					</label>
				</div> <!-- .form-group -->

				<div class="form-group">
					<label class="control-sidebar-subheading">
						Turn off notifications
						<input type="checkbox" class="pull-right">
					</label>
				</div> <!-- .form-group -->

				<div class="form-group">
					<label class="control-sidebar-subheading">
						Delete chat history
						<a href="javascript:void(0)" class="text-red pull-right">
							<i class="fa fa-trash-o"></i>
						</a>
					</label>
				</div> <!-- .form-group -->
			</form>
		</div> <!-- .tab-pane -->
	</div>
</aside> <!-- .control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

resources/views/partials/css.blade.php
{{ Html::style('public/plugin/select2-4.0.3/dist/css/select2.min.css') }}
{{ Html::style('public/plugin/plyr-3.4.4/dist/plyr.css') }}
{{ Html::style('public/plugin/AdminLTE-2.4.5/bower_components/bootstrap/dist/css/bootstrap.min.css') }}
{{ Html::style('public/plugin/AdminLTE-2.4.5/bower_components/font-awesome/css/font-awesome.min.css') }}
{{ Html::style('public/plugin/AdminLTE-2.4.5/bower_components/Ionicons/css/ionicons.min.css') }}
{{ Html::style('public/plugin/AdminLTE-2.4.5/dist/css/AdminLTE.min.css') }}
{{ Html::style('public/plugin/AdminLTE-2.4.5/dist/css/skins/_all-skins.min.css') }}
{{ Html::style('public/plugin/AdminLTE-2.4.5/bower_components/morris.js/morris.css') }}
{{ Html::style('public/plugin/AdminLTE-2.4.5/bower_components/jvectormap/jquery-jvectormap.css') }}
{{ Html::style('public/plugin/AdminLTE-2.4.5/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}
{{ Html::style('public/plugin/AdminLTE-2.4.5/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}
{{ Html::style('public/plugin/AdminLTE-2.4.5/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}
{{ Html::style('public/plugin/AdminLTE-2.4.5/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}

<!-- {{ Html::style('public/plugin/Semantic-UI-CSS-master/semantic.min.css') }} -->

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

resources/views/partials/footer.blade.php
<footer class="main-footer">
	<!-- To the right -->
	<div class="pull-right hidden-xs">
		<b>Version</b> 2.4.0
	</div>
	<!-- Default to the left -->
	<strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
</footer>

resources/views/partials/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

<title>@yield('title') - Ujikom</title>

<meta name="description" content="">

<link rel="icon" href="{{ asset('public/kuremi-icon.png') }}">

@include('partials.css')

@yield('stylesheets')

resources/views/partials/header.blade.php
<header class="main-header">
	<!-- Logo -->
	<a href="index2.html" class="logo">
		<!-- mini logo for sidebar mini 50x50 pixels -->
		<span class="logo-mini">
			<img src="{{ asset('public/kuremi-icon.png')}}" alt="">
		</span>
		<!-- logo for regular state and mobile devices -->
		<span class="logo-lg"><b>Ujikom</b></span>
	</a>

	<!-- Header Navbar: style can be found in header.less -->
	<nav class="navbar navbar-static-top">
		<!-- Sidebar toggle button-->
		<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
			<span class="sr-only">Toggle navigation</span>
		</a>

		<div class="navbar-custom-menu">
			<ul class="nav navbar-nav">
				<!-- Messages: style can be found in dropdown.less-->
				<li class="dropdown messages-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="fa fa-envelope-o"></i>
						<span class="label label-success">4</span>
					</a>
					<ul class="dropdown-menu">
						<li class="header">You have 4 messages</li>

						<li>
							<!-- inner menu: contains the actual data -->
							<ul class="menu">
								<!-- start message -->
								<li>
									<a href="#">
										<div class="pull-left">
											<img src="{{ asset('public/plugin/AdminLTE-2.4.5/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
										</div>
										<h4>
											Support Team
											<small><i class="fa fa-clock-o"></i> 5 mins</small>
										</h4>
										<p>Why not buy a new awesome theme?</p>
									</a>
								</li> <!-- .end message -->

								<li>
									<a href="#">
										<div class="pull-left">
											<img src="{{ asset('public/plugin/AdminLTE-2.4.5/dist/img/user3-128x128.jpg') }}" class="img-circle" alt="User Image">
										</div>
										<h4>
											AdminLTE Design Team
											<small><i class="fa fa-clock-o"></i> 2 hours</small>
										</h4>
										<p>Why not buy a new awesome theme?</p>
									</a>
								</li>

								<li>
									<a href="#">
										<div class="pull-left">
											<img src="{{ asset('public/plugin/AdminLTE-2.4.5/dist/img/user4-128x128.jpg') }}" class="img-circle" alt="User Image">
										</div>
										<h4>
											Developers
											<small><i class="fa fa-clock-o"></i> Today</small>
										</h4>
										<p>Why not buy a new awesome theme?</p>
									</a>
								</li>

								<li>
									<a href="#">
										<div class="pull-left">
											<img src="{{ asset('public/plugin/AdminLTE-2.4.5/dist/img/user3-128x128.jpg') }}" class="img-circle" alt="User Image">
										</div>
										<h4>
											Sales Department
											<small><i class="fa fa-clock-o"></i> Yesterday</small>
										</h4>
										<p>Why not buy a new awesome theme?</p>
									</a>
								</li>

								<li>
									<a href="#">
										<div class="pull-left">
											<img src="{{ asset('public/plugin/AdminLTE-2.4.5/dist/img/user4-128x128.jpg') }}" class="img-circle" alt="User Image">
										</div>
										<h4>
											Reviewers
											<small><i class="fa fa-clock-o"></i> 2 days</small>
										</h4>
										<p>Why not buy a new awesome theme?</p>
									</a>
								</li>

							</ul>
						</li>

						<li class="footer"><a href="#">See All Messages</a></li>
					</ul>
				</li>

				<!-- Notifications: style can be found in dropdown.less -->
				<li class="dropdown notifications-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="fa fa-bell-o"></i>
						<span class="label label-warning">10</span>
					</a>
					<ul class="dropdown-menu">
						<li class="header">You have 10 notifications</li>
						<li>
							<!-- inner menu: contains the actual data -->
							<ul class="menu">

								<li>
									<a href="#">
										<i class="fa fa-users text-aqua"></i> 5 new members joined today
									</a>
								</li>

								<li>
									<a href="#">
										<i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
									</a>
								</li>

								<li>
									<a href="#">
										<i class="fa fa-users text-red"></i> 5 new members joined
									</a>
								</li>

								<li>
									<a href="#">
										<i class="fa fa-shopping-cart text-green"></i> 25 sales made
									</a>
								</li>

								<li>
									<a href="#">
										<i class="fa fa-user text-red"></i> You changed your username
									</a>
								</li>

							</ul>
						</li>
						<li class="footer"><a href="#">View all</a></li>
					</ul>
				</li>

				<!-- Tasks: style can be found in dropdown.less -->
				<li class="dropdown tasks-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="fa fa-flag-o"></i>
						<span class="label label-danger">9</span>
					</a>
					<ul class="dropdown-menu">
						<li class="header">You have 9 tasks</li>
						<li>
							<!-- inner menu: contains the actual data -->
							<ul class="menu">
								<!-- Task item -->
								<li>
									<a href="#">
										<h3>
											Design some buttons
											<small class="pull-right">20%</small>
										</h3>
										<div class="progress xs">
											<div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
												<span class="sr-only">20% Complete</span>
											</div>
										</div>
									</a>
								</li> <!-- .end task item -->

								<li>
									<a href="#">
										<h3>
											Create a nice theme
											<small class="pull-right">40%</small>
										</h3>
										<div class="progress xs">
											<div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
												<span class="sr-only">40% Complete</span>
											</div>
										</div>
									</a>
								</li>

								<li>
									<a href="#">
										<h3>
											Some task I need to do
											<small class="pull-right">60%</small>
										</h3>
										<div class="progress xs">
											<div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
												<span class="sr-only">60% Complete</span>
											</div>
										</div>
									</a>
								</li>

								<li>
									<a href="#">
										<h3>
											Make beautiful transitions
											<small class="pull-right">80%</small>
										</h3>
										<div class="progress xs">
											<div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
												<span class="sr-only">80% Complete</span>
											</div>
										</div>
									</a>
								</li>

							</ul>
						</li>
						<li class="footer"><a href="#">View all tasks</a></li>
					</ul>
				</li>

				<!-- User Account: style can be found in dropdown.less -->
				<li class="dropdown user user-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<img src="{{ asset('public/plugin/AdminLTE-2.4.5/dist/img/user2-160x160.jpg') }}" class="user-image" alt="User Image">
						<span class="hidden-xs">Alexander Pierce</span>
					</a>
					<ul class="dropdown-menu">
						<!-- User image -->
						<li class="user-header">
							<img src="{{ asset('public/plugin/AdminLTE-2.4.5/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">

							<p>
								Alexander Pierce - Web Developer
								<small>Member since Nov. 2012</small>
							</p>
						</li>
						<!-- Menu Body -->
						<li class="user-body">
							<div class="row">
								<div class="col-xs-4 text-center">
									<a href="#">Followers</a>
								</div>
								<div class="col-xs-4 text-center">
									<a href="#">Sales</a>
								</div>
								<div class="col-xs-4 text-center">
									<a href="#">Friends</a>
								</div>
							</div> <!-- .row -->
						</li>
						<!-- Menu Footer-->
						<li class="user-footer">
							<div class="pull-left">
								<a href="#" class="btn btn-default btn-flat">Profile</a>
							</div>
							<div class="pull-right">
								<a href="#" class="btn btn-default btn-flat">Sign out</a>
							</div>
						</li>
					</ul>
				</li>

				<!-- Control Sidebar Toggle Button -->
				<li>
					<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
				</li>
			</ul>
		</div>
	</nav>
</header>

resources/views/partials/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
		<!-- Sidebar user panel -->
		<div class="user-panel">
			<div class="pull-left image">
				<img src="{{ asset('public/plugin/AdminLTE-2.4.5/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
			</div>
			<div class="pull-left info">
				<p>Alexander Pierce</p>
				<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
			</div>
		</div>

		<!-- sidebar menu: : style can be found in sidebar.less -->
		<ul class="sidebar-menu" data-widget="tree">

			<li class="treeview {{ Request::is('') ? 'active' : '' }}">
				<a href="{{ route('home') }}">
					<i class="fa fa-dashboard"></i> <span>Dashboard</span>
				</a>
			</li>

			<li>
				<a href="#">
					<i class="fa fa-book"></i> <span>Documentation</span>
				</a>
			</li>

			<!-- <li class="treeview {{ Request::is('user') ? 'active' : '' }}">
				<a href="#">
					<i class="fa fa-users"></i> <span>Users</span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<ul class="treeview-menu">
					<li>
						<a href="#">
							<i class="fa fa-circle-o"></i> <span>Add User</span>
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fa fa-circle-o"></i> <span>View Users</span>
						</a>
					</li>
				</ul>
			</li> -->

			<li class="treeview {{ Request::is('supplier', 'supplier/create') ? 'active' : '' }}">
				<a href="#">
					<i class="fa fa-signal"></i> <span>Supplier</span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<ul class="treeview-menu">
					<li>
						<a href="{{ route('supplier.create') }}">
							<i class="fa fa-circle-o"></i> <span>Add Supplier</span>
						</a>
					</li>
					<li>
						<a href="{{ route('supplier.index') }}">
							<i class="fa fa-circle-o"></i> <span>View Supplier</span>
						</a>
					</li>
				</ul>
			</li>

			<li class="treeview {{ Request::is('barangmasuk', 'barangmasuk/create') ? 'active' : '' }}">
				<a href="#">
					<i class="fa fa-bolt"></i> <span>Barang Masuk</span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<ul class="treeview-menu">
					<li>
						<a href="{{ route('barangmasuk.create') }}">
							<i class="fa fa-circle-o"></i> <span>Add Barang Masuk</span>
						</a>
					</li>
					<li>
						<a href="{{ route('barangmasuk.index') }}">
							<i class="fa fa-circle-o"></i> <span>View Barang Masuk</span>
						</a>
					</li>
				</ul>
			</li>

			<!-- <li class="treeview {{ Request::is('barang', 'barang/create') ? 'active' : '' }}">
				<a href="#">
					<i class="fa fa-align-center"></i> <span>Barang</span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<ul class="treeview-menu">
					<li>
						<a href="{{ route('barang.create') }}">
							<i class="fa fa-circle-o"></i> <span>Add Barang</span>
						</a>
					</li>
					<li>
						<a href="{{ route('barang.index') }}">
							<i class="fa fa-circle-o"></i> <span>View Barang</span>
						</a>
					</li>
				</ul>
			</li> -->

			<li class="treeview {{ Request::is('barangkeluar', 'barangkeluar/create') ? 'active' : '' }}">
				<a href="#">
					<i class="fa fa-paperclip"></i> <span>Barang Keluar</span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<ul class="treeview-menu">
					<li>
						<a href="{{ route('barangkeluar.create') }}">
							<i class="fa fa-circle-o"></i> <span>Add Barang Keluar</span>
						</a>
					</li>
					<li>
						<a href="{{ route('barangkeluar.index') }}">
							<i class="fa fa-circle-o"></i> <span>View Barang Keluar</span>
						</a>
					</li>
				</ul>
			</li>

			<!-- <li class="treeview {{ Request::is('pinjambarang', 'pinjambarang/create') ? 'active' : '' }}">
				<a href="#">
					<i class="fa fa-calendar"></i> <span>Pinjam Barang</span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<ul class="treeview-menu">
					<li>
						<a href="{{ route('pinjambarang.create') }}">
							<i class="fa fa-circle-o"></i> <span>Add Pinjam Barang</span>
						</a>
					</li>
					<li>
						<a href="{{ route('pinjambarang.index') }}">
							<i class="fa fa-circle-o"></i> <span>View Pinjam Barang</span>
						</a>
					</li>
				</ul>
			</li> -->

			<li class="treeview {{ Request::is('stok', 'stok/create') ? 'active' : '' }}">
				<a href="#">
					<i class="fa fa-suitcase"></i> <span>Stoks</span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<ul class="treeview-menu">
					<!-- <li>
						<a href="{{ route('stok.create') }}">
							<i class="fa fa-circle-o"></i> <span>Add Stok</span>
						</a>
					</li> -->
					<li>
						<a href="{{ route('stok.index') }}">
							<i class="fa fa-circle-o"></i> <span>View Stoks</span>
						</a>
					</li>
				</ul>
			</li>

			<li>
				<a href="{{ route('logout') }}"
					onclick="event.preventDefault();
					document.getElementById('logout-form').submit();">
					<i class="fa fa-sign-out"></i> <span>Sign Out</span>
				</a>
				<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
					@csrf
				</form>
			</li>

		</ul>
	</section> <!-- .sidebar -->
</aside>